"""Add POI table

Revision ID: 0d1e49057ce0
Revises: bc7160a1a7b7
Create Date: 2018-12-04 22:31:14.860337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1e49057ce0'
down_revision = 'bc7160a1a7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poi_type', sa.String(length=12), nullable=True),
    sa.Column('long_logic', sa.String(length=50), nullable=True),
    sa.Column('short_logic', sa.String(length=50), nullable=True),
    sa.Column('common_logic', sa.String(length=255), nullable=True),
    sa.Column('long_params', sa.String(length=32), nullable=True),
    sa.Column('short_params', sa.String(length=32), nullable=True),
    sa.Column('vars', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pois')
    # ### end Alembic commands ###
