"""add protoype_parameters table

Revision ID: 339816130d48
Revises: 59d7119663a4
Create Date: 2018-12-10 09:45:53.119169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339816130d48'
down_revision = '59d7119663a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prototype_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proto_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('input_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['proto_id'], ['prototypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prototype_parameters')
    # ### end Alembic commands ###
