"""candidate settings

Revision ID: 543c75d60433
Revises: d88915e0f144
Create Date: 2018-12-28 11:13:58.819810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543c75d60433'
down_revision = 'd88915e0f144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_settings')
    # ### end Alembic commands ###
