"""market internals status field

Revision ID: 56d07a659137
Revises: 59bec7ee1263
Create Date: 2018-11-08 14:15:24.064216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d07a659137'
down_revision = '59bec7ee1263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_internal_optimizations', sa.Column('end_run', sa.DateTime(), nullable=True))
    op.add_column('market_internal_optimizations', sa.Column('start_run', sa.DateTime(), nullable=True))
    op.add_column('market_internal_optimizations', sa.Column('status', sa.String(length=12), nullable=True))
    op.add_column('market_internal_optimizations', sa.Column('status_state', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_internal_optimizations', 'status_state')
    op.drop_column('market_internal_optimizations', 'status')
    op.drop_column('market_internal_optimizations', 'start_run')
    op.drop_column('market_internal_optimizations', 'end_run')
    # ### end Alembic commands ###
