"""market internals file field

Revision ID: 59bec7ee1263
Revises: 8b0b3c63195b
Create Date: 2018-11-08 14:12:14.158774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59bec7ee1263'
down_revision = '8b0b3c63195b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_internal_optimizations', sa.Column('mi_file', sa.String(length=250), nullable=True))
    op.add_column('market_internal_optimizations', sa.Column('oos_end_dt', sa.Date(), nullable=True))
    op.add_column('market_internal_optimizations', sa.Column('oos_start_dt', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_internal_optimizations', 'oos_start_dt')
    op.drop_column('market_internal_optimizations', 'oos_end_dt')
    op.drop_column('market_internal_optimizations', 'mi_file')
    # ### end Alembic commands ###
