"""modify playlist type

Revision ID: 59d7119663a4
Revises: f4accffcde96
Create Date: 2018-12-05 19:19:32.579390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d7119663a4'
down_revision = 'f4accffcde96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oos_tests', 'drawdown_day',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('oos_tests', 'drawdown_intra',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('oos_tests', 'percent_winners',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('oos_tests', 'rina',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('oos_tests', 'trade_count',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('playlists', 'list_type',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlists', 'list_type',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    op.alter_column('oos_tests', 'trade_count',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('oos_tests', 'rina',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               existing_nullable=True)
    op.alter_column('oos_tests', 'percent_winners',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('oos_tests', 'drawdown_intra',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('oos_tests', 'drawdown_day',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
