"""added jcl version

Revision ID: 5c3a0b080d5a
Revises: 9e9d752064ec
Create Date: 2018-12-30 22:15:10.317021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3a0b080d5a'
down_revision = '9e9d752064ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proto_configs', sa.Column('jcl_version', sa.String(length=12), nullable=True))
    op.alter_column('proto_configs', 'template_version',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proto_configs', 'template_version',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.drop_column('proto_configs', 'jcl_version')
    # ### end Alembic commands ###
