"""create dow_optimizations table

Revision ID: 627092a314ca
Revises: c4fe3d66d764
Create Date: 2018-11-18 20:00:01.630347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627092a314ca'
down_revision = 'c4fe3d66d764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dow_optimizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strat_id', sa.Integer(), nullable=True),
    sa.Column('sec_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=12), nullable=True),
    sa.Column('dow_file', sa.String(length=250), nullable=True),
    sa.Column('oos_start_dt', sa.Date(), nullable=True),
    sa.Column('oos_end_dt', sa.Date(), nullable=True),
    sa.Column('dow_switch', sa.String(length=12), nullable=True),
    sa.Column('dow_parameter', sa.String(length=12), nullable=True),
    sa.Column('entry_exit_both', sa.String(length=12), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('status_state', sa.String(length=12), nullable=True),
    sa.Column('start_run', sa.DateTime(), nullable=True),
    sa.Column('end_run', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sec_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['strat_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dow_optimizations')
    # ### end Alembic commands ###
