"""empty message

Revision ID: 91124475036a
Revises: 257ec322016e
Create Date: 2018-11-15 15:00:09.720850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91124475036a'
down_revision = '257ec322016e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'profit_ring_1')
    op.drop_column('strategies', 'consistency_ring_center')
    op.drop_column('strategies', 'profit_ring_2')
    op.drop_column('strategies', 'wfe_ring_1')
    op.drop_column('strategies', 'wfe_ring_2')
    op.drop_column('strategies', 'wfe_ring_center')
    op.drop_column('strategies', 'consistency_ring_2')
    op.drop_column('strategies', 'profit_ring_center')
    op.drop_column('strategies', 'consistency_ring_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('consistency_ring_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('strategies', sa.Column('profit_ring_center', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('strategies', sa.Column('consistency_ring_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('strategies', sa.Column('wfe_ring_center', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('strategies', sa.Column('wfe_ring_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('strategies', sa.Column('wfe_ring_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('strategies', sa.Column('profit_ring_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('strategies', sa.Column('consistency_ring_center', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('strategies', sa.Column('profit_ring_1', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
