"""added re_optimization

Revision ID: 9e9d752064ec
Revises: 543c75d60433
Create Date: 2018-12-28 11:37:35.613337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9d752064ec'
down_revision = '543c75d60433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prototype_parameters', sa.Column('re_optimize', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prototype_parameters', 're_optimize')
    # ### end Alembic commands ###
