"""create ef_optimizations table

Revision ID: bc7160a1a7b7
Revises: 627092a314ca
Create Date: 2018-11-28 19:28:52.997762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7160a1a7b7'
down_revision = '627092a314ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ef_optimizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strat_id', sa.Integer(), nullable=True),
    sa.Column('sec_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=12), nullable=True),
    sa.Column('opt_file', sa.String(length=250), nullable=True),
    sa.Column('oos_start_dt', sa.Date(), nullable=True),
    sa.Column('oos_end_dt', sa.Date(), nullable=True),
    sa.Column('i_switch', sa.String(length=12), nullable=True),
    sa.Column('i_parameter', sa.String(length=12), nullable=True),
    sa.Column('i_entry_exit_both', sa.String(length=12), nullable=True),
    sa.Column('i_reset_on_day', sa.String(length=12), nullable=True),
    sa.Column('i_reset_after_exit', sa.String(length=12), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('status_state', sa.String(length=12), nullable=True),
    sa.Column('start_run', sa.DateTime(), nullable=True),
    sa.Column('end_run', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sec_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['strat_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('strat_id_tmp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strat_id_tmp',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_table('ef_optimizations')
    # ### end Alembic commands ###
