from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fe3d66d764'
down_revision = 'd2861fdc7b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
