"""add proto_config table

Revision ID: c65b4a226165
Revises: 4bde7c253676
Create Date: 2018-12-14 12:16:50.256662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65b4a226165'
down_revision = '4bde7c253676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proto_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sec_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('template_version', sa.String(length=12), nullable=False),
    sa.Column('data_set', sa.Integer(), nullable=True),
    sa.Column('data_block', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=12), nullable=True),
    sa.Column('chart_series', sa.String(length=255), nullable=True),
    sa.Column('fitness_function', sa.String(length=12), nullable=True),
    sa.Column('max_days_back', sa.Integer(), nullable=True),
    sa.Column('trades_per_day', sa.String(length=12), nullable=True),
    sa.Column('day_swing', sa.String(length=12), nullable=True),
    sa.Column('prestart_dt', sa.Date(), nullable=True),
    sa.Column('start_dt', sa.Date(), nullable=True),
    sa.Column('end_dt', sa.Date(), nullable=True),
    sa.Column('bt_start_dt', sa.Date(), nullable=True),
    sa.Column('bt_end_dt', sa.Date(), nullable=True),
    sa.Column('in_sample_file', sa.String(length=128), nullable=True),
    sa.Column('out_of_sample_file', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('status_state', sa.String(length=12), nullable=True),
    sa.Column('start_run', sa.DateTime(), nullable=True),
    sa.Column('end_run', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sec_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proto_configs')
    # ### end Alembic commands ###
