"""added cols to strategies

Revision ID: d2861fdc7b47
Revises: d90741b0c626
Create Date: 2018-11-17 21:08:09.651239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2861fdc7b47'
down_revision = 'd90741b0c626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('dow_id', sa.Integer(), nullable=True))
    op.add_column('strategies', sa.Column('dow_n1', sa.Integer(), nullable=True))
    op.add_column('strategies', sa.Column('dow_n2', sa.Integer(), nullable=True))
    op.add_column('strategies', sa.Column('dow_opt', sa.Integer(), nullable=True))
    op.add_column('strategies', sa.Column('mi_opt', sa.Integer(), nullable=True))
    op.add_column('strategies', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('strategies', sa.Column('strat_type', sa.String(length=12), nullable=True))
    op.drop_column('strategies', 'mi_optimized')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('mi_optimized', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('strategies', 'strat_type')
    op.drop_column('strategies', 'parent_id')
    op.drop_column('strategies', 'mi_opt')
    op.drop_column('strategies', 'dow_opt')
    op.drop_column('strategies', 'dow_n2')
    op.drop_column('strategies', 'dow_n1')
    op.drop_column('strategies', 'dow_id')
    # ### end Alembic commands ###
