"""version 2 of candidate tables

Revision ID: d88915e0f144
Revises: fe75fddbbbb2
Create Date: 2018-12-28 11:09:54.307756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88915e0f144'
down_revision = 'fe75fddbbbb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_configs', 'strategy_file',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('candidate_configs', 'strategy_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('candidate_configs', 'template_version',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.drop_constraint('candidate_configs_session_id_fkey', 'candidate_configs', type_='foreignkey')
    op.drop_constraint('candidate_configs_sec_id_fkey', 'candidate_configs', type_='foreignkey')
    op.drop_column('candidate_configs', 'chart_series')
    op.drop_column('candidate_configs', 'symbol')
    op.drop_column('candidate_configs', 'bt_end_dt')
    op.drop_column('candidate_configs', 'sec_id')
    op.drop_column('candidate_configs', 'bt_start_dt')
    op.drop_column('candidate_configs', 'end_dt')
    op.drop_column('candidate_configs', 'start_dt')
    op.drop_column('candidate_configs', 'fitness_function')
    op.drop_column('candidate_configs', 'day_swing')
    op.drop_column('candidate_configs', 'trades_per_day')
    op.drop_column('candidate_configs', 'session_id')
    op.drop_column('candidate_configs', 'max_bars_back')
    op.add_column('candidate_parameters', sa.Column('range', sa.String(length=255), nullable=False))
    op.drop_constraint('candidate_parameters_candidate_id_fkey', 'candidate_parameters', type_='foreignkey')
    op.create_foreign_key(None, 'candidate_parameters', 'candidate_configs', ['candidate_id'], ['id'])
    op.drop_column('candidate_parameters', 'input_type')
    op.drop_column('candidate_parameters', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_parameters', sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('candidate_parameters', sa.Column('input_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'candidate_parameters', type_='foreignkey')
    op.create_foreign_key('candidate_parameters_candidate_id_fkey', 'candidate_parameters', 'candidates', ['candidate_id'], ['id'])
    op.drop_column('candidate_parameters', 'range')
    op.add_column('candidate_configs', sa.Column('max_bars_back', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('candidate_configs', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('candidate_configs', sa.Column('trades_per_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('candidate_configs', sa.Column('day_swing', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('candidate_configs', sa.Column('fitness_function', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.add_column('candidate_configs', sa.Column('start_dt', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('candidate_configs', sa.Column('end_dt', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('candidate_configs', sa.Column('bt_start_dt', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('candidate_configs', sa.Column('sec_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('candidate_configs', sa.Column('bt_end_dt', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('candidate_configs', sa.Column('symbol', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.add_column('candidate_configs', sa.Column('chart_series', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key('candidate_configs_sec_id_fkey', 'candidate_configs', 'markets', ['sec_id'], ['id'])
    op.create_foreign_key('candidate_configs_session_id_fkey', 'candidate_configs', 'sessions', ['session_id'], ['id'])
    op.alter_column('candidate_configs', 'template_version',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('candidate_configs', 'strategy_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('candidate_configs', 'strategy_file',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
