"""add entry_filters

Revision ID: f4accffcde96
Revises: d5a6c3d906a6
Create Date: 2018-12-05 19:13:15.240179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4accffcde96'
down_revision = 'd5a6c3d906a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_type', sa.String(length=12), nullable=True),
    sa.Column('long_logic', sa.String(length=50), nullable=True),
    sa.Column('short_logic', sa.String(length=50), nullable=True),
    sa.Column('common_logic', sa.String(length=255), nullable=True),
    sa.Column('long_params', sa.String(length=32), nullable=True),
    sa.Column('short_params', sa.String(length=32), nullable=True),
    sa.Column('vars', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_filters')
    # ### end Alembic commands ###
