"""capture reopt interation count

Revision ID: 0cf92a1f2ae8
Revises: eab6eaf085ad
Create Date: 2019-01-02 00:48:42.788720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf92a1f2ae8'
down_revision = 'eab6eaf085ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('reopt_iterations', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'reopt_iterations')
    # ### end Alembic commands ###
