"""add opt_param_names to candidates

Revision ID: 1de2da384120
Revises: 3cdefa0f485b
Create Date: 2019-01-31 08:19:48.219054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de2da384120'
down_revision = '3cdefa0f485b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('reopt_param_names', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'reopt_param_names')
    # ### end Alembic commands ###
