"""refactor strategy tabels, step 2

Revision ID: 27707a678afd
Revises: 380f7d0d2596
Create Date: 2019-02-01 22:57:48.117298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27707a678afd'
down_revision = '380f7d0d2596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_oos_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('start_dt', sa.Date(), nullable=True),
    sa.Column('end_dt', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_oos_periods')
    # ### end Alembic commands ###
