"""change column name from range to value

Revision ID: 2b3ff44fa98b
Revises: 0cf92a1f2ae8
Create Date: 2019-01-02 01:15:38.073935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3ff44fa98b'
down_revision = '0cf92a1f2ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_parameters', sa.Column('value', sa.String(length=255), nullable=True))
    op.alter_column('candidate_parameters', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_column('candidate_parameters', 'range')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_parameters', sa.Column('range', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('candidate_parameters', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('candidate_parameters', 'value')
    # ### end Alembic commands ###
