"""add dates and status to strategy settings

Revision ID: 3cdefa0f485b
Revises: 9839179a15c8
Create Date: 2019-01-29 14:37:02.880523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cdefa0f485b'
down_revision = '9839179a15c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_settings', sa.Column('end_dt', sa.Date(), nullable=True))
    op.add_column('strategy_settings', sa.Column('start_dt', sa.Date(), nullable=True))
    op.add_column('strategy_settings', sa.Column('status', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_settings', 'status')
    op.drop_column('strategy_settings', 'start_dt')
    op.drop_column('strategy_settings', 'end_dt')
    # ### end Alembic commands ###
