"""expanded prototypes jcl/strat tempaltes to 32

Revision ID: 554ee7746a50
Revises: 75eb533a948e
Create Date: 2019-01-12 09:30:16.785981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554ee7746a50'
down_revision = '75eb533a948e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prototypes', 'jcl_version',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('prototypes', 'template_version',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prototypes', 'template_version',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    op.alter_column('prototypes', 'jcl_version',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    # ### end Alembic commands ###
