"""added run_rank with default 10 to candidates

Revision ID: 75eb533a948e
Revises: e58ecc9b7dfd
Create Date: 2019-01-11 13:15:56.825451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75eb533a948e'
down_revision = 'e58ecc9b7dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('run_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'run_rank')
    # ### end Alembic commands ###
