"""refactor strategy tabels, step 3

Revision ID: 9153f11e889d
Revises: 27707a678afd
Create Date: 2019-02-01 22:58:58.093741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9153f11e889d'
down_revision = '27707a678afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_oos_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('data_type', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['strategy_oos_periods.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_oos_settings')
    # ### end Alembic commands ###
