"""add bt_start_dt and bt_end_dt to candidates

Revision ID: 9839179a15c8
Revises: da89ae5ac97f
Create Date: 2019-01-22 22:09:55.218843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9839179a15c8'
down_revision = 'da89ae5ac97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('bt_end_dt', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('bt_start_dt', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'bt_start_dt')
    op.drop_column('candidates', 'bt_end_dt')
    # ### end Alembic commands ###
