"""Added job_controls table

Revision ID: 9a5a36ccb66f
Revises: 8d3ace135928
Create Date: 2019-01-08 12:11:53.245967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5a36ccb66f'
down_revision = '8d3ace135928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_status', sa.String(length=32), nullable=True),
    sa.Column('app_name', sa.String(length=32), nullable=True),
    sa.Column('host_name', sa.String(length=32), nullable=True),
    sa.Column('session_max_runs', sa.Integer(), nullable=True),
    sa.Column('session_max_mins', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_controls')
    # ### end Alembic commands ###
