"""add opt_param_names to strategies

Revision ID: a85cba9861e4
Revises: 1de2da384120
Create Date: 2019-01-31 17:27:47.084453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85cba9861e4'
down_revision = '1de2da384120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('reopt_param_names', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'reopt_param_names')
    # ### end Alembic commands ###
