"""add WFA data to candidates

Revision ID: a959213efd74
Revises: 9a5a36ccb66f
Create Date: 2019-01-09 12:59:08.369495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a959213efd74'
down_revision = '9a5a36ccb66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('number_of_trades', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('opt_iterations', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('reopt_bars', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('reopt_days', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('reopt_string', sa.String(length=250), nullable=True))
    op.drop_column('candidates', 'reopt_iterations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('reopt_iterations', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('candidates', 'reopt_string')
    op.drop_column('candidates', 'reopt_days')
    op.drop_column('candidates', 'reopt_bars')
    op.drop_column('candidates', 'opt_iterations')
    op.drop_column('candidates', 'number_of_trades')
    # ### end Alembic commands ###
