"""created logic_repo to consolidate pois and entry_filters

Revision ID: bee420876c22
Revises: c071aa1d1391
Create Date: 2019-01-13 17:25:47.754147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee420876c22'
down_revision = 'c071aa1d1391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logic_repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logic_type', sa.String(length=32), nullable=True),
    sa.Column('long_logic', sa.String(length=256), nullable=True),
    sa.Column('short_logic', sa.String(length=256), nullable=True),
    sa.Column('common_logic', sa.String(length=256), nullable=True),
    sa.Column('long_params', sa.String(length=32), nullable=True),
    sa.Column('short_params', sa.String(length=32), nullable=True),
    sa.Column('vars', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logic_repos')
    # ### end Alembic commands ###
