"""expanded candidates jcl/strat tempaltes to 32

Revision ID: c071aa1d1391
Revises: 554ee7746a50
Create Date: 2019-01-12 09:31:23.016305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c071aa1d1391'
down_revision = '554ee7746a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'jcl_version',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('candidates', 'template_version',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'template_version',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    op.alter_column('candidates', 'jcl_version',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    # ### end Alembic commands ###
