"""create strategy table

Revision ID: c8e9704f66f4
Revises: 7adaad5439f9
Create Date: 2019-01-19 22:28:48.038270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e9704f66f4'
down_revision = '7adaad5439f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cand_id', sa.Integer(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('market_session_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=12), nullable=True),
    sa.Column('chart_series', sa.String(length=255), nullable=True),
    sa.Column('robust_level', sa.Integer(), nullable=True),
    sa.Column('strategy_file', sa.String(length=250), nullable=True),
    sa.Column('strategy_name', sa.String(length=250), nullable=True),
    sa.Column('reopt_iterations', sa.Integer(), nullable=True),
    sa.Column('reopt_days', sa.Integer(), nullable=True),
    sa.Column('reopt_bars', sa.Integer(), nullable=True),
    sa.Column('reopt_string', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('status_state', sa.String(length=12), nullable=True),
    sa.Column('start_run', sa.DateTime(), nullable=True),
    sa.Column('end_run', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cand_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['market_session_id'], ['market_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategies')
    # ### end Alembic commands ###
