"""create table parameter_definitions

Revision ID: ccd19a55a946
Revises: f9eaf08ff96a
Create Date: 2019-01-01 18:44:22.696764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd19a55a946'
down_revision = 'f9eaf08ff96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('step_size', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('data_type', sa.String(length=32), nullable=True),
    sa.Column('num_steps', sa.Integer(), nullable=True),
    sa.Column('re_opt', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameter_definitions')
    # ### end Alembic commands ###
