"""add template versions to strategies

Revision ID: da89ae5ac97f
Revises: e2305e2c27e7
Create Date: 2019-01-22 20:48:37.213429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da89ae5ac97f'
down_revision = 'e2305e2c27e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('jcl_version', sa.String(length=32), nullable=True))
    op.add_column('strategies', sa.Column('oos_curve_template_v', sa.String(length=32), nullable=True))
    op.add_column('strategies', sa.Column('strategy_template_v', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'strategy_template_v')
    op.drop_column('strategies', 'oos_curve_template_v')
    op.drop_column('strategies', 'jcl_version')
    # ### end Alembic commands ###
