"""create strategy_reopt_parameters

Revision ID: e2305e2c27e7
Revises: e52f978b8649
Create Date: 2019-01-22 19:43:23.792686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2305e2c27e7'
down_revision = 'e52f978b8649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_reopt_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('data_type', sa.String(length=8), nullable=True),
    sa.Column('input_type', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_reopt_parameters')
    # ### end Alembic commands ###
