"""added run_rank with default 10 to prototypes

Revision ID: e58ecc9b7dfd
Revises: a959213efd74
Create Date: 2019-01-11 13:13:22.746231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58ecc9b7dfd'
down_revision = 'a959213efd74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prototypes', sa.Column('run_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prototypes', 'run_rank')
    # ### end Alembic commands ###
