"""initial migration

Revision ID: f9eaf08ff96a
Revises: 
Create Date: 2018-12-31 16:22:48.919479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9eaf08ff96a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_type', sa.String(length=32), nullable=True),
    sa.Column('long_logic', sa.String(length=256), nullable=True),
    sa.Column('short_logic', sa.String(length=256), nullable=True),
    sa.Column('common_logic', sa.String(length=256), nullable=True),
    sa.Column('long_params', sa.String(length=32), nullable=True),
    sa.Column('short_params', sa.String(length=32), nullable=True),
    sa.Column('vars', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_start', sa.Integer(), nullable=True),
    sa.Column('session_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poi_type', sa.String(length=12), nullable=True),
    sa.Column('long_logic', sa.String(length=50), nullable=True),
    sa.Column('short_logic', sa.String(length=50), nullable=True),
    sa.Column('common_logic', sa.String(length=255), nullable=True),
    sa.Column('long_params', sa.String(length=32), nullable=True),
    sa.Column('short_params', sa.String(length=32), nullable=True),
    sa.Column('vars', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('mkt_type', sa.String(length=12), nullable=True),
    sa.Column('symbol', sa.String(length=12), nullable=True),
    sa.Column('ts_symbol', sa.String(length=12), nullable=True),
    sa.Column('ts_status', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('group_1', sa.String(length=32), nullable=True),
    sa.Column('value_1_tick', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ticks_per_point', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('margin_init', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('margin_maint', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('margin_day', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('comm_entry_dol', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('comm_exit_dol', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('slippage_entry_tick', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('slippage_exit_tick', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['market_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prototypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('market_session_id', sa.Integer(), nullable=True),
    sa.Column('template_version', sa.String(length=12), nullable=True),
    sa.Column('jcl_version', sa.String(length=12), nullable=True),
    sa.Column('data_set', sa.Integer(), nullable=True),
    sa.Column('data_block', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=12), nullable=True),
    sa.Column('chart_series', sa.String(length=255), nullable=True),
    sa.Column('fitness_function', sa.String(length=12), nullable=True),
    sa.Column('max_days_back', sa.Integer(), nullable=True),
    sa.Column('trades_per_day', sa.String(length=12), nullable=True),
    sa.Column('day_swing', sa.String(length=12), nullable=True),
    sa.Column('prestart_dt', sa.Date(), nullable=True),
    sa.Column('start_dt', sa.Date(), nullable=True),
    sa.Column('end_dt', sa.Date(), nullable=True),
    sa.Column('bt_start_dt', sa.Date(), nullable=True),
    sa.Column('bt_end_dt', sa.Date(), nullable=True),
    sa.Column('in_sample_file', sa.String(length=128), nullable=True),
    sa.Column('out_of_sample_file', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('status_state', sa.String(length=12), nullable=True),
    sa.Column('start_run', sa.DateTime(), nullable=True),
    sa.Column('end_run', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['market_session_id'], ['market_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proto_id', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('template_version', sa.String(length=12), nullable=True),
    sa.Column('jcl_version', sa.String(length=12), nullable=True),
    sa.Column('strategy_file', sa.String(length=250), nullable=True),
    sa.Column('strategy_name', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('status_state', sa.String(length=12), nullable=True),
    sa.Column('start_run', sa.DateTime(), nullable=True),
    sa.Column('end_run', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proto_id'], ['prototypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prototype_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proto_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('input_type', sa.String(length=32), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('data_type', sa.String(length=8), nullable=True),
    sa.Column('re_optimize', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['proto_id'], ['prototypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('range', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=8), nullable=True),
    sa.Column('input_type', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('data_type', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_settings')
    op.drop_table('candidate_parameters')
    op.drop_table('prototype_parameters')
    op.drop_table('candidates')
    op.drop_table('prototypes')
    op.drop_table('markets')
    op.drop_table('pois')
    op.drop_table('market_sessions')
    op.drop_table('entry_filters')
    # ### end Alembic commands ###
